HSIEO-5475: Support user-defined classes
Beiming-Zhang/zpm pull request #2
Opened 2022-01-13 09:48 UTC by Beiming-Zhang

* Support customizable composite class and packagemanager class during init of zpm.
* Create empty(deafult) packagemanager class.
* Changes needed on %ZHSLIB side: 
* 1. %ZHSLIB.PackageManager.Developer.Extension.SourceControl.Interface needs to extend %ZPM.PackageManager.Developer.Extension.SourceControl.Interface
* 2. %ZHSLIB.PackageManager.Developer.Extension.CompositeMethodOverrides needs to extend %ZPM.PackageManager.Developer.Extension.CompositeMethodOverrides
* WIP: Add better descriptions & helper msgs

2022-01-13 10:24 UTC, isc-kiyer requested changes
Just one comment and flagging TODOs so we don't forget about them. Looks good otherwise.

2022-01-13 10:24 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager.cls
> +		$$$ThrowOnError($Classmethod(tCompositeSCClass, SetExtensionClasses(tOldSourceControlClass,$ListBuild(tPackageMgrSCClass))))
This call is incorrect. Need to pass separate arguments when using $ClassMethod:
```
$ClassMethod(tCompositeSCClass, "SetExtensionClasses", tOldSourceControlClass, $ListBuild(tPackageMgrSCClass))
```

2022-01-13 10:24 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager.cls
> +<modifier name="compositeClass" aliases="compcls" value="true" description="composite class to use; will update with better description later" />
Flagging TODO for later

2022-01-13 10:24 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager.cls
> +		Set tResponse = ##class(%Library.Prompt).GetYesNo("Do you want to use a non-default composite class for this namespace?",.tResult,.tHelp)
Flagging TODO for later

2022-01-13 10:24 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager.cls
> +		Set tHelp = "What is a packageMgr class? - Will update later"
Flagging default for later

2022-01-14 22:32 UTC, Beiming-Zhang commented
@isc-kiyer  I just realized that the changed required is not as easy as I've done in this PR : ( . Basically, we need a way for IPM to remember the composite & PM extension class forever, just as it remembers the source control class. I think we should at least provide such or similar functionalities in one of the Interface or override classes. For example, storing them in a fixed global. How do you think?

2022-01-20 16:12 UTC, closed without merging