HSIEO-5499: Rename ZPM classes
Beiming-Zhang/zpm pull request #3
Opened 2022-01-14 21:45 UTC by Beiming-Zhang

* Part 1: Class 1-30 of the renaming file
* Continue working
[Copy of zpm_to_ipm_rename.xlsx](https://github.com/Beiming-Zhang/zpm/files/7873392/Copy.of.zpm_to_ipm_rename.xlsx)

2022-01-20 20:57 UTC, isc-kiyer requested changes
Great work! Especially amazing considering there are so many files but such few errors.
Some final notes:
1. Put back the DEFAULTGLOBAL parameter.
2. Update the spreadsheet with decisions made on any additional class renames/moving classes to other repos
3. Fix the rename/move items flagged as TODO

2022-01-20 20:57 UTC, isc-kiyer commented on module.xml
>    <API>
If we are removing API annotation stuff, everything in the <API> tag will go away

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/CLI.cls
> +	Write $$$EscapeOrFormat(pCommandName, ##class(%ZPM.Main).TerminalPromptColor())
%ZPM.Main is a subclass of this class so this sort of dependency isn't great. The TerminalPromptColor() method should be moved into this class and referenced using .. instead.

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/DataType/ResourceName.cls
> +Class %ZPM.DataType.ResourceName Extends %ZPM.DataType.RegExString [ ClassType = datatype ]
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager/Developer/Processor/CSPApplication.cls
> -Class %ZPM.PackageManager.Developer.Processor.CSPApplication Extends (%ZPM.PackageManager.Developer.Processor.Abstract, %XML.Adaptor, %Installer.CSPApplication) [ PropertyClass = %ZPM.PackageManager.
Actually keep this for now and we will deprecate it because it is widely used despite it's side effects. Should be named %ZPM.ResourceProcessor.CSPApplication. Also update in spreadsheet once done.

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager/Server/SemVerFind.cls
Perhaps rename class to %ZPM.General.SemanticVersion.Find? I added it to the google sheet

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/PackageManager/Server/SemVerIndex.cls
>  /// </p>
Perhaps rename to %ZPM.General.SemanticVersion.Index? I added it to the google sheet

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Definition.cls
> +SELECT Name FROM %ZPM_Repo.Definition
Good decision to use full table name and good catch!

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Filesystem/Definition.cls
> +		&sql(delete from %ZPM_REPO_Filesystem.Cache where Root = :tOldRoot)
Should be %ZPM_Repo_Filesystem.Cache

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> +	Set tNSMenu($i(tNSMenu)) = "Install an application (not yet supported)"
This entire method can be removed instead as it is specific to Application packaging instead of Module. Also remove the corresponding reference in ShellInternal() and the command from the XData block.

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> -  Set tSource = $Get(pCommandInfo("parameters","source"))
Why is this removed?

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> -		Set tLoadFlags = $Select(tCompile:"c",1:"")_$Select(tQuiet:"-d",tVerbose:"d",1:"")_"k"
Why remove ref to tQuiet?

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> -      Continue:tListOnly&&'$IsObject(%SourceControl)
Why is this removed?

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> +					Set tSC = $System.OBJ.LoadDir(tSourceDir,,tLoadFlags,,tRecurse,.tImportedArray,tListOnly)
This should remain ImportDir()

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> -      Continue:'$IsObject(%SourceControl)
Why is this removed?

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Main.cls
> +					Do %SourceControl.GetStatus(tLoadedItem,.tIsInSourceControl)
What are these changes? Even if they are well warranted/required, do not belong in this PR

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Lifecycle/Base.cls
> +		// Set tSC = ..Module.UpdateAPIDocumentation(tModuleDependencies)
Can just delete. No need to comment out.

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Filesystem/PackageService.cls
> +Class %ZPM.Repo.Filesystem.PackageService Extends (%RegisteredObject, %ZPM.Repo.IPackageService)
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/IPackageService.cls
> +Class %ZPM.Repo.IPackageService [ Abstract ]
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/IPublishService.cls
> +Class %ZPM.Repo.IPublishService [ Abstract ]
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Local/Definition.cls
> +Class %ZPM.Repo.Local.Definition Extends %ZPM.Repo.Definition
This entire class can be deleted

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Manager.cls
> +			If pForceRemoteRepo && tServer.%IsA("%ZPM.Repo.Local.Definition") {
Can remove this if statement as Local.Definition is removed

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Manager.cls
> +			If pForceRemoteRepo && tServer.%IsA("%ZPM.Repo.Local.Definition") {
Can remove as Local.Definition is removed

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Remote/ModuleInfo.cls
> +Parameter XMLTYPE = "CoreModule";
Why is a different XMLTYPE needed? Please add a comment to the parameter explaining if it is required

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Remote/ModuleInfo.cls
> +		Set tXData = ##class(%Dictionary.XDataDefinition).%OpenId("%ZPM.Repo.Remote.ModuleInfo||ManifestTransform",,.tSC)
Nit: Can use $Classname() here instead of hard-coding the class name

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Remote/PublishService.cls
> +Class %ZPM.Repo.Remote.PublishService Extends (%ZPM.Repo.Remote.PackageService, %ZPM.Repo.IPublishService)
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Repo/Utils.cls
> +Class %ZPM.Repo.Utils
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/ResourceProcessor/LocalizationExport.cls
> +Class %ZPM.ResourceProcessor.LocalizationExport Extends %ZPM.ResourceProcessor.Abstract
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/ResourceProcessor/LocalizationExport/MsgDomain.cls
> +Class %ZPM.ResourceProcessor.LocalizationExport.MsgFile Extends (%RegisteredObject, %XML.Adaptor)
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/ResourceProcessor/LocalizationExport/MsgFile.cls
> +Class %ZPM.ResourceProcessor.LocalizationExport.MsgFile Extends (%RegisteredObject, %XML.Adaptor)
TODO: Do rename/move

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Storage/LoadedResource.cls
> +<IdLocation>^ZPM.Storage.LoadedResourceD</IdLocation>
This should be a ^IRIS.Temp global via DEFAULTGLOBAL parameter

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Storage/ModuleTemplate.cls
> +    Set currentNamespace = $Namespace
Why change this? The call could be passing another namespace not equal to $Namespace as an argument right?

2022-01-20 20:57 UTC, isc-kiyer commented on src/cls/_ZPM/Storage/ModuleTemplate.cls
> +Method AddWebApps(pApps As %String, Output cspapps As %List) As %Status
Again no need to remove the argument. Leave as is so namespace can be overridden

2022-01-20 20:57 UTC, isc-kiyer commented on src/inc/_ZPM/PackageManager/Developer/Annotation.inc
> +ROUTINE %ZPM.PackageManager.Developer.Annotation [Type=INC] /// macro versions
This can be removed as just used by annotations. Also remove from module.xml

2022-01-20 20:57 UTC, isc-kiyer commented on tests/integration_tests/Test/PM/Integration/_data/simple-app/cls/TSL/Lifecycle.xml
>  <Class name="TSL.Lifecycle">
Delete the class and references to it since application packaging removed

2022-01-20 20:57 UTC, isc-kiyer commented on tests/integration_tests/Test/PM/Integration/_data/simple-app/cls/TSL/TestInstaller.xml
>  <Class name="TSL.TestInstaller">
Delete the class and references to it since installer removed

2022-01-22 01:07 UTC, merged

2022-01-22 01:48 UTC, Beiming-Zhang commented
Reopening